export const REWRITE= 'rewriteUserInfo'
export const NEWSLIST='getNewsList'
export const COACHLIST='getCoachList'
export const LESSON='getLesson'
export const AUTOLOGIN='getIsLogin'
export const ENTRANCE='getEntrance'
export const LOGOUT='getLogout'
export const CHANGEAVATAR='changeAvatar'
export const NEWS='getNews'
export const COMMENT='postComment'

